apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: us-central1-docker.pkg.dev/project-1ed2c8e0-2f81-48df-b18/sofe3980u/binarycalculator:latest
        ports:
        - containerPort: 8080
